### PR TITLE
Bookmark feature

### LINKED ISSUE #5: Architecture: Add Realm Caching

### PR DESCRIPTION
**Pull request by samuelrey**
- [x] Create bookmarks tab to view all bookmarks
- [x] Create bookmark button
- [x] Toggle between add bookmark and remove bookmark
- [x] Cache post ids locally
- [x] Design bookmark button consistently

Fixes #5

### CODE REVIEW

**Comment by samuelrey** [comment]
Opened the PR to show what I have so far.
At the moment, the app will crash when opening the bookmark tab because the adapter expects Post objects but gets the Bookmark object instead. See [#95 in the API repo](https://github.com/SoftwareEngineeringDaily/software-engineering-daily-api/issues/95)

**Comment by TheHollidayInn** [comment]
This is looking great so far :D Good work!

**Comment by TheHollidayInn** [comment]
I see you requested my review, is this good to test? Your check list is 3/5

**Comment by samuelrey** [comment]
I didn't request a review unless it was done automatically when I pushed changes :O
I'm working on fixing the merge conflicts atm.

**Comment by TheHollidayInn** [comment]
Sounds good!

**Comment by TheHollidayInn** [comment]
@samuelrey How's it going with this?

**Comment by samuelrey** [comment]
Hey @TheHollidayInn 
I've just started a new job & am still finding my bearings. I'm sorry to say that I don't think I can actively work on this feature.

**Comment by TheHollidayInn** [comment]
No worries! I'll finish it off :) Thanks for the work and congrats on the new job!

**Comment by samuelrey** [comment]
Thank you! I'll definitely stay subscribed to the project :D

**Comment by TheHollidayInn** [comment]
Merging in manually.

**Pull request closed without merging**
