### PR TITLE
Feature/kotlin support

### PR DESCRIPTION
**Pull request by kvithayathil**
Adding Kotlin compatibility
Setting compile target [to Java 8](https://developer.android.com/studio/write/java8-support.html)

### CODE REVIEW

**Comment by TheHollidayInn** [comment]
Awesome!

**Comment by Tofuus** [comment]
I'm a big fan of Kotlin, but I'm a little concerned about it adding another hurdle for new contributors. It may potentially limit our contributors to people who know both Java and Kotlin.

**Comment by TheHollidayInn** [comment]
That's a pretty good point. I actually haven't been pushing Kotlin because Google hasn't officially supported it yet, but now they do with Android Studio 3.

1. I am working on a from scratch to modern Android guide I hope will get users quickly up to speed with the ecosystem
2. I think we can restrict kotlin to advance/not commonly used items first. We will do the switch in small steps. This PR only enables the feature.

**Comment by kvithayathil** [comment]
Definitely a valid point @Tofuus. The intention is just to add capability, not necessarily act as a way to start turning everything into Kotlin. As @TheHollidayInn mentioned, my thinking is that potentially it could be used in narrow scenarios or even just writing the unit tests. I still am of the assumption that this primarily a Java-based app.

We'll have to establish guidelines as to when to use Kotlin vs Java.

**Comment by TheHollidayInn** [comment]
Did you mean to close this?

**Comment by kvithayathil** [comment]
whoops, just re-opened

**Review by Tofuus — APPROVED** [review]

**Comment by kvithayathil** [comment]
Resolved conflicts with develop

**Pull request merged**
