### PR TITLE
- Updating Travis configuration

### PR DESCRIPTION
**Pull request by kvithayathil**
- Adding dev build type with stub google-services.json
- Fixed build issues with android build tools

This may not be the most optimal configuration but now it at least builds and runs.

### CODE REVIEW

**Comment by TheHollidayInn** [comment]
Thank you!!! 

Do you have docs to explain some of the setup?

**Comment by TheHollidayInn** [comment]
Eh, nvm. I see what you did now. This is great

**Comment by kvithayathil** [comment]
No problem - was mostly googling and trial and error. Still wrapping my head around some of this stuff :) Once I get a better understanding of the finer details I can probably optimize it further

**Comment by TheHollidayInn** [comment]
Oh this was based on the wrong branch.

**Comment by kvithayathil** [comment]
well this was a merge to your existing travis branch. You can double check that before merging in to develop

**Comment by TheHollidayInn** [comment]
Yea, for sure. I didn’t realize :P

**Pull request merged**
